filebeat.inputs:
- type: container
  paths:
    - '/var/lib/docker/containers/*/*.log'

output.logstash:
  hosts: ["172.16.188.5:5044"]

processors:
- add_docker_metadata:
    host: "unix:///var/run/docker.sock"

- decode_json_fields:
    fields: ["message"]
    target: "json"
    overwrite_keys: true

logging.json: true
logging.metrics.enabled: false