metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

metricbeat.modules:
- module: docker
  metricsets: ["container", "cpu", "diskio", "event", "healthcheck", "memory", "network", "network_summary"]
  hosts: ["unix:///var/run/docker.sock"]
  period: 10s

output.logstash:
  hosts: ["172.16.188.5:5044"]