---
- name: Install zabbix agent
  hosts: all
  become: yes

  roles:
    - install_zabbix_agent

- name: Configure active check on jenkins
  hosts: jenkins
  become: yes

  roles:
    - configure_zabbix_agent_docker
