version: '3.8'
services:
  php:
    build:
      context: ./php
    volumes:
      - './html:/var/www/html'
    depends_on:
      - mariadb

  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    links:
      - 'php'
    volumes:
      - './html:/var/www/html'
      - './conf.d:/etc/nginx/conf.d'

  mariadb:
    image: mariadb:10.3.9
    env_file:
      db.env